method: bayes
metric:
    goal: minimize
    name: best_valid_loss
parameters:
    beta_shift:
        distribution: categorical
        values:
        - 0.25
        - 0.3
        - 0.35
        - 0.4
        - 0.45
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1
        - 1.5
        - 1.8
        - 2
        - 2.2
        - 2.5
        - 2.8
        - 3
        - 3.2
        - 3.4
        - 3.6
        - 3.8
        - 4
        - 4.5
        - 4.8
        - 5
        - 5.5
        - 5.8
        - 6
        - 6.2
        - 6.4
        - 7
        - 8
        - 10
        - 12
        - 14
        - 16
        - 20
        - 22
        - 24
        - 28
        - 30
        - 32
        - 40
        - 44
        - 50
        - 60
        - 70
        - 80
        - 100
    dataset:
        distribution: categorical
        values:
        - humor
    dropout_prob:
        distribution: uniform
        max: 0.8
        min: 0.25
    gradient_accumulation_step:
        distribution: int_uniform
        max: 8
        min: 1
    learning_rate:
        distribution: categorical
        values:
        - 0.0001
        - 0.0003
        - 0.0005
        - 1e-05
        - 3e-05
        - 5e-05
        - 1e-06
        - 3e-06
        - 5e-06
    max_seq_length:
        distribution: int_uniform
        max: 80
        min: 25
    model:
        distribution: categorical
        values:
        - xlnet-base-cased
    n_epochs:
        distribution: int_uniform
        max: 20
        min: 10
    train_batch_size:
        distribution: categorical
        values:
        - 64
    warmup_proportion:
        distribution: uniform
        max: 0.3
        min: 0.05
program: multimodal_driver.py
